spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/markit
    username: markit
    password: markit
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: order_service
  flyway:
    create-schemas: true
    schemas: order_service
  kafka:
    bootstrap-servers: kafka:9092

app:
  product-service:
    url: http://product-service:8082