server:
  port: 8086

spring:
  application:
    name: admin-server
  boot:
    admin:
      ui:
        title: Markit Admin
        brand: "<img src='https://via.placeholder.com/40'><span>Markit Admin</span>"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
