plugins {
	id 'java-library'
}

dependencies {
	api 'org.springframework:spring-web'
	api 'org.springframework:spring-context'
	api 'org.slf4j:slf4j-api'
	api 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
	compileOnly 'jakarta.servlet:jakarta.servlet-api'
	compileOnly 'org.springframework.boot:spring-boot'
	compileOnly 'org.springframework.boot:spring-boot-autoconfigure'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
}