spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/markit
    username: markit
    password: markit
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: product_service
  flyway:
    create-schemas: true
    schemas: product_service
  kafka:
    bootstrap-servers: kafka:9092